# Generated by Django 4.2.14 on 2024-08-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField()),
                ('tran_type', models.IntegerField()),
                ('tran_class', models.IntegerField()),
                ('cart_currency', models.CharField(max_length=3)),
                ('language', models.CharField(max_length=3)),
                ('hide_shipping', models.BooleanField(default=True)),
                ('callback_url', models.URLField()),
                ('return_url', models.URLField()),
                ('tokenise', models.IntegerField(default=2)),
                ('framed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('transaction_status', models.CharField(max_length=10)),
                ('transaction_amount', models.FloatField()),
                ('transaction_currency', models.CharField(max_length=3)),
                ('transaction_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=10)),
                ('identifier', models.CharField(max_length=20)),
                ('profile_id', models.IntegerField()),
            ],
        ),
    ]
