# Generated by Django 4.2.14 on 2024-08-09 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='callback_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='return_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='tran_class',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='config',
            name='tran_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
